name: openaisummarizer
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - conda-forge::python-sounddevice
  - conda-forge::ffmpeg
  - conda-forge::pysoundfile
  - conda-forge::openai
  - conda-forge::pydub
  - conda-forge::portaudio
  - conda-forge::cryptography
  - anaconda::tk
